import type { GalleryImage } from "@/lib/content-types";

export const localGalleryImages: GalleryImage[] = [
  { id: "bano", url: "/images/gallery/Baño.jpg", alt: "Baño" },
  { id: "clase", url: "/images/gallery/Clase.jpg", alt: "Clase" },
  { id: "clinica", url: "/images/gallery/Clinica.jpg", alt: "Clínica" },
  { id: "clinica-2", url: "/images/gallery/Clinica2.jpg", alt: "Clínica 2" },
  { id: "clinica-3", url: "/images/gallery/Clinica3.jpg", alt: "Clínica 3" },
  { id: "entrada", url: "/images/gallery/Entrada.jpg", alt: "Entrada" },
  { id: "paciente", url: "/images/gallery/Paciente.jpg", alt: "Paciente" },
  { id: "paciente-2", url: "/images/gallery/Paciente2.jpg", alt: "Paciente 2" },
  { id: "paciente-3", url: "/images/gallery/Paciente3.jpg", alt: "Paciente 3" },
  { id: "pilates", url: "/images/gallery/Pilates.jpg", alt: "Pilates" },
  { id: "powerexplosive", url: "/images/gallery/Powerexplosive.jpg", alt: "Power Explosive" },
  { id: "recepcion", url: "/images/gallery/Recepcion.jpg", alt: "Recepción" },
  { id: "recepcion-2", url: "/images/gallery/Recepcion2.jpg", alt: "Recepción 2" },
  { id: "rouco", url: "/images/gallery/Rouco.jpg", alt: "Rouco" },
  { id: "sala", url: "/images/gallery/Sala.jpg", alt: "Sala" },
  { id: "sala-2", url: "/images/gallery/Sala2.jpg", alt: "Sala 2" },
  { id: "sala-3", url: "/images/gallery/Sala3.jpg", alt: "Sala 3" },
  { id: "sala-espera", url: "/images/gallery/Salaespera.jpg", alt: "Sala de espera" },
  { id: "sala-espera-2", url: "/images/gallery/Salaespera2.jpg", alt: "Sala de espera 2" },
  { id: "galeria-1", url: "/images/gallery/Galeria1.jpeg", alt: "Clase de pilates" },
  { id: "galeria-2", url: "/images/gallery/Galeria2.jpeg", alt: "Ejercicio en grupo" },
  { id: "galeria-3", url: "/images/gallery/Galeria3.jpeg", alt: "Clase de rehabilitación" },
  { id: "galeria-4", url: "/images/gallery/Galeria4.jpeg", alt: "Trabajo de core" },
  { id: "galeria-5", url: "/images/gallery/Galeria5.jpeg", alt: "Entrenamiento funcional" },
  { id: "galeria-6", url: "/images/gallery/Galeria6.jpeg", alt: "Sesión grupal" },
  { id: "galeria-7", url: "/images/gallery/Galeria7.jpeg", alt: "Ejercicio con fitball" },
  { id: "galeria-8", url: "/images/gallery/Galeria8.jpeg", alt: "Tratamiento con kinesiotape" },
  { id: "galeria-9", url: "/images/gallery/Galeria9.jpeg", alt: "Masaje terapéutico" },
  { id: "galeria-10", url: "/images/gallery/Galeria10.jpeg", alt: "Electropunción" },
  { id: "galeria-11", url: "/images/gallery/Galeria11.jpeg", alt: "Tratamiento de rodilla" },
  { id: "galeria-12", url: "/images/gallery/Galeria12.jpeg", alt: "Valoración de pie" },
  { id: "galeria-13", url: "/images/gallery/Galeria13.jpeg", alt: "Tratamiento con punción seca" },
  { id: "galeria-14", url: "/images/gallery/Galeria14.jpeg", alt: "Fisioterapia deportiva" },
  { id: "galeria-15", url: "/images/gallery/Galeria15.jpeg", alt: "Sala de ejercicios" },
];
